### ISSUE TITLE
secret milvus-operator-webhook-cert not found

### ISSUE THREAD

**Issue by xxyp** [milvus-io/milvus-operator#101]
when use helm to install milvus-operator.tar.gz, secret milvus-operator-webhook-cert can not be found

**Comment by haorenfsa** [comment]
@xxyp It's not created immediatelly. There's a check Job which will create the secret `milvus-operator-webhook-cert` for you in a couple of minutes. 

Could you provide more info?  Such as your install command, logs etc...
