### ISSUE TITLE
Didn't find settings of pulsar 

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus-operator#105]
I didn't find anywhere to config pulsar defaultRetentionTimeInMinutes.
There are many other settings in helm we should backport to K8s operator

**Comment by xiaofan-luan** [comment]
> I didn't find anywhere to config pulsar defaultRetentionTimeInMinutes. There are many other settings in helm we should backport to K8s operator

Might be similar to etcd and minio

**Comment by haorenfsa** [comment]
Dependencies now all referenced from  https://github.com/milvus-io/milvus-helm;  so the values files are removed.
- [ ] README to be updated
- [ ] provide an all fields configuration sample: not merged, can be found in: https://github.com/milvus-io/milvus-operator/pull/97/files

**Comment by haorenfsa** [comment]
Detailed descriptions can be found in https://github.com/milvus-io/milvus-operator/blob/main/docs/administration/manage-dependencies/message-storage.md
