### ISSUE TITLE
Supports configuring service account for the Pods.

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/milvus-operator#123]
This is a subtask for milvus' IAM access support for S3 storage https://github.com/milvus-io/milvus/issues/16898

**Comment by ganderaj** [comment]
@haorenfsa 

I have gone through couple of existing issues but it is unclear to me on the IAM Role support for S3 Access. 

Does the latest release of Milvus supports IAM Role for Service Accounts ([IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)) for S3 access on Milvus ? If yes, can you please guide me to the documentation ?

**Comment by haorenfsa** [comment]
@ganderaj Yes, check this sample https://github.com/zilliztech/milvus-operator/blob/main/config/samples/milvus_s3_iam.yaml

**Comment by ganderaj** [comment]
@haorenfsa 

Appreciate your prompt support with relevant article. We have deployed Milvus on AWS EKS using [zilliztech/milvus-helm](https://github.com/zilliztech/milvus-helm). 

Can we use [zilliztech/milvus-operator](https://github.com/zilliztech/milvus-operator) to update/add configurations or upgrade a cluster deployed using milvus-helm ? If yes, does a milvus-operator have intelligence to recognize cluster details automatically or do we have to share details explicitly ?

**Comment by haorenfsa** [comment]
It's not a feature by design, but maybe workable.

You can try write a `Milvus` CRD manifest based on your current helm deploy. The `metadata.name` & `metadata.namespace` field should be the same as your current helm release. Apply it to your EKS, so milvus-operator will be able to observe this milvus and to take over.
For some historical reasons, there may be some differences in the pod template & pod labels. So maybe milvus components or depedencies (etcd / pulsar) will be restarted.

**Comment by ganderaj** [comment]
Thanks, I'll keep you posted with my findings.
