### ISSUE TITLE
Enable RBAC

### ISSUE THREAD

**Issue by kish5432** [milvus-io/milvus-operator#247]
HI Team,

I tried to enable rbac on milvus cluster by including below snippet in milvus.yaml file. But still getting error while creating a "Role".
spec:
  mode: cluster
  # Omit other fields ...
  components:
    # use the above ServiceAccount
    serviceAccountName: milvus
    #image: milvusdb/milvus-dev:master-latest
    proxy:
      serviceType: LoadBalancer
      replicas: 2  
  config:
    log:
      level: debug
    minio:
      cloudProvider: aws
      # your bucket name
      bucketName: milvus-s3
      rootPath: milvus/s3-access
      # Optional, config the prefix of the bucket milvus will use 
      useSSL: true
      useIAM: true
    auth:
      rbac:
        enabled: true
  dependencies:
    etcd:
      inCluster:

**Error:**
>>> from pymilvus import utility
>>> role_name = "readOnly"
>>> role = Role(role_name, using=_CONNECTION)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Role' is not defined

Please guide and share some sample yaml file or suggest the section(config, dependencies etc)where to add rbac code snippet in yam.
Thanks in advance.

**Comment by haorenfsa** [comment]
Hi, the `Role` class is defined  in `pymilvus` package. So you could either:
```python
import pymilvus
# ...
role = pymilvus.Role(role_name, using=_CONNECTION)
```

or:

```python
from pymilvus import Role
# ...
role = Role(role_name, using=_CONNECTION)
```

And about the guide, check the [Document section of the README file](https://github.com/milvus-io/milvus-operator#documentations). and rbac operation examples can be found in [milvus.io](https://milvus.io/docs/rbac.md).

It seems that you were following the latter, and indeed it doesn't mention you should import `Role` in `pymilvus` package. We'll fix that soon. Thank you very much for the feedback

**Comment by kish5432** [comment]
thank you @haorenfsa...its working now
