### ISSUE TITLE
operator has no secret "milvus-operator-webhook-cert"

### ISSUE THREAD

**Issue by free-bird-a** [milvus-io/milvus-operator#275]
when I deploy milvus operator with file of "deployment.yaml", I got an error, 'secret "milvus-operator-webhook-cert" not found'.
no secret named milvus-operator-webhook-cert created before deploy milvus operator, how to fix it?

**Comment by haorenfsa** [comment]
check this issue https://github.com/milvus-io/milvus/issues/23985

**Comment by free-bird-a** [comment]
TKS. Solved
